Diploma_work/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Diploma_work.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult PointsBuilder()
        {
            return View();
        }

        public ActionResult RouteBuilder()
        {
            return View();
        }
    }
}

Diploma_work/Controllers/PointsController.cs
using CsvHelper;
using Diploma_work.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.VisualBasic.FileIO;

namespace Diploma_work.Controllers
{
    public class PointsController : Controller
    {
        [HttpPost]
        [ActionName("GetPoint")]
        [Route("[controller]/{searchRequest}")]
        public ActionResult GetPoint(string searchRequest)
        {
            string url = "https://nominatim.openstreetmap.org/search?q={0}&format=json&polygon=0&addressdetails=1";
            HttpClient client = new HttpClient();
            string cityName = searchRequest.Replace(' ', '+');

            client.DefaultRequestHeaders.Add("user-agent", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; .NET CLR 1.0.3705;)");
            var response = client.GetAsync(string.Format(url, cityName)).Result;
            HttpContent content = response.Content;

            Task<String> result = content.ReadAsStringAsync();
            List<RootObject> rootList = new List<RootObject>();

            rootList = JsonConvert.DeserializeObject<List<RootObject>>(result.Result);

            List<SearchResult> searchResultList = new List<SearchResult>();

            SearchResult searchResult = new SearchResult();

            foreach (var item in rootList)
            {
                searchResultList.Add(
                    new SearchResult
                    {
                        place_id = item.place_id,
                        osm_id = item.osm_id,
                        osm_type = item.osm_type,
                        lat = item.lat,
                        lon = item.lon,
                        display_name = item.display_name,
                        type = item.type,
                        importance = item.importance,
                        icon = item.icon,
                        city = item.address.city,
                        state = item.address.state,
                        postcode = item.address.postcode,
                        country = item.address.country,
                        country_code = item.address.country_code
                    });
            }
            return Json(searchResultList);
        }

        [HttpPost]
        [ActionName("GetPoints")]
        //[Route("[controller]/{searchRequest}")]
        public ActionResult GetPointsCSV(HttpPostedFileBase file)
        {
            List<CSVModel> CSVList = new List<CSVModel>();
            
            var fileName = Path.GetFileName(file.FileName);

            using (TextFieldParser csvParser = new TextFieldParser(fileName))
            {
                csvParser.SetDelimiters(new string[] { "," });
                csvParser.HasFieldsEnclosedInQuotes = true;

                csvParser.ReadLine();

                while (!csvParser.EndOfData)
                {
                    // Read current line fields, pointer moves to the next line.
                    string[] fields = csvParser.ReadFields();

                    CSVModel Record = new CSVModel();

                    Record.id = Int32.Parse(fields[0]);
                    Record.name = fields[1];
                    Record.latitude = Double.Parse(fields[2].Replace('.', ','));
                    Record.longitude = Double.Parse(fields[3].Replace('.', ','));

                    CSVList.Add(Record);
                }

                //CsvReader csv = new CsvReader(reader);
                //csv.Configuration.Delimiter = ",";
                //csv.Configuration.MissingFieldFound = null;
                //while (csv.Read())
                //{
                //    CSVModel Record = csv.GetRecord<CSVModel>();
                //    CSVList.Add(Record);
                //}
            }

            return Json(CSVList);
        }
    }

    public class Address
    {
        public string city { get; set; }
        public string state { get; set; }
        public string postcode { get; set; }
        public string country { get; set; }
        public string country_code { get; set; }
        public string county { get; set; }
        public string station { get; set; }
        public string road { get; set; }
        public string suburb { get; set; }
        public string hotel { get; set; }
        public string house_number { get; set; }
        public string supermarket { get; set; }
        public string cafe { get; set; }
        public string information { get; set; }
        public string water { get; set; }
        public string village { get; set; }
        public string address29 { get; set; }
        public string guest_house { get; set; }
    }

    public class RootObject
    {
        public string place_id { get; set; }
        public string licence { get; set; }
        public string osm_type { get; set; }
        public string osm_id { get; set; }
        public List<string> boundingbox { get; set; }
        public string lat { get; set; }
        public string lon { get; set; }
        public string display_name { get; set; }
        public string @class { get; set; }
        public string type { get; set; }
        public double importance { get; set; }
        public string icon { get; set; }
        public Address address { get; set; }
    }

    public class SearchResult
    {
        public string place_id { get; set; }
        public string licence { get; set; }
        public string osm_type { get; set; }
        public string osm_id { get; set; }
        //public List<string> boundingbox { get; set; }
        public string lat { get; set; }
        public string lon { get; set; }
        public string display_name { get; set; }
        public string type { get; set; }
        public double importance { get; set; }
        public string icon { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postcode { get; set; }
        public string country { get; set; }
        public string country_code { get; set; }
        public string county { get; set; }
        public string station { get; set; }
        public string road { get; set; }
        public string suburb { get; set; }
        public string hotel { get; set; }
        public string house_number { get; set; }
        public string supermarket { get; set; }
        public string cafe { get; set; }
        public string information { get; set; }
        public string water { get; set; }
        public string village { get; set; }
        public string address29 { get; set; }
        public string guest_house { get; set; }
    }
}

Diploma_work/Views/Home/PointsBuilder.cshtml
@{
    ViewBag.Title = "PointsBuilder";
}

<h2>PointsBuilder</h2>

@using (Html.BeginForm("GetPoints", "Points", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="file" />
    <input type="submit" name="Submit" id="Submit" value="Upload" />
}

<div class="input-group">
    <input id="search-line" type="text" class="form-control" placeholder="Search for...">
    <span class="input-group-btn">
        <button id="search-button" onclick="" class="btn btn-secondary" type="button">Go!</button>
    </span>
</div>
<div class="col-md-12" style="padding-top:15px;">
    <div class="col-md-5" id="search-result">
    </div>

    <div class="mapContent col-md-7" id="content" style="height: 350px; float: right;">
        @*<div class="loader loader-default"></div>*@
    </div>
</div>
<script type="text/javascript">

    var searchBtn = document.getElementById('search-button');

    window.onload = function () {
        sessionStorage.clear();
        sessionStorage.setItem("mapIsCreate", "false");
    }

    var spinner = $('.mapContent').children('.loader');

    searchBtn.onclick = function () {

        //spinner.addClass('is-active')

        var searchLine = document.getElementById('search-line');

        //if (sessionStorage.getItem("mapIsCreate") == "false") {

        //    this.map = new L.map('content').setView([0, 0], 2);
        //    sessionStorage.setItem("mapIsCreate", "true");
        //}
        //else {
        //    map.remove();
        //    this.map = new L.map('content').setView([0, 0], 2);
        //}

        //var markers = L.markerClusterGroup();

        var xhr = new XMLHttpRequest(),
            method = 'POST',
            url = '/Points/GetPoint/';

        xhr.open(method, url, true);
        xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
        xhr.send('searchRequest=' + searchLine.value);

        xhr.onload = function () {

            var searchResult = document.getElementById('search-result');
            var parcedResponse = JSON.parse(xhr.response);

            var table = '<div class="results_sidebar" id="sidebar">';

            parcedResponse.forEach(function (item, index) {

                var json = item;

                //for (var value in json) {
                //    if (json[value] == null) {
                //        json[value] = '';
                //    }
                //}

                var coordinates = '[' + json.lat + ',' + json.lon + ']'

                if (index == 0) {
                    table += '<div id="result" class="result active" position="' + index + '" onclick="printPoint(' + index + ',' + coordinates + ')">'
                }
                else {
                    table += '<div id="result" class="result" position="' + index + '" onclick="printPoint(' + index + ',' + coordinates + ')">'
                }
                table += '<span class="name">' + json.display_name + '</span>'
                table += '<span class="type">(' + json.type + ')</span>'
                table += '</div>'
            })

            table += '</div>';
            searchResult.innerHTML = table;

            //console.log(parcedResponse);
            //for (var i = 0; i < parcedResponse.length; i++) {
            //    var coord = parcedResponse[i].split(',');
            //    var marker = L.marker([coord[0], coord[1]]);
            //    marker.bindPopup("Lat: " + coord[0] + " " + "Long: " + coord[1]);
            //    markers.addLayer(marker);
            //}

            //map.addLayer(markers);
            //spinner.removeClass('is-active');
        }

        //L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiZ29vb2dpbGkiLCJhIjoiY2o5dHB2eGRtNGZ2cTJxcGdkZWNzbDh0MiJ9.EkOgfmQR4JzFno4YpWMK6A', {
        //    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        //    minZoom: 2,
        //    maxZoom: 18,
        //    id: 'mapbox.streets',
        //    accessToken: 'pk.eyJ1IjoiZ29vb2dpbGkiLCJhIjoiY2o5dHB2eGRtNGZ2cTJxcGdkZWNzbDh0MiJ9.EkOgfmQR4JzFno4YpWMK6A'
        //}).addTo(map);
    }

    function printPoint(index, coordinates) {

        var header = document.getElementById("sidebar");
        var btns = header.getElementsByClassName("result");
        var current = document.getElementsByClassName("active");
        current[0].className = current[0].className.replace(" active", "");
        btns[index].className += " active";

        spinner.addClass('is-active');


        if (sessionStorage.getItem("mapIsCreate") == "false") {
            this.map = new L.map('content').setView([coordinates[0], coordinates[1]], 15);
            sessionStorage.setItem("mapIsCreate", "true");
        }
        else {
            map.remove();
            this.map = new L.map('content').setView([coordinates[0], coordinates[1]], 15);
        }

        //var markers = L.markerClusterGroup();

        //var coord = parcedResponse[index].coordinates.split(',');
        var marker = L.marker([coordinates[0], coordinates[1]]).addTo(map);
        marker.bindPopup("Lat: " + coordinates[0] + " " + "Long: " + coordinates[1]);
        //markers.addLayer(marker);

        //for (var i = 0; i < parcedResponse.length; i++) {
        //    var coord = parcedResponse[i].split(',');
        //    var marker = L.marker([coord[0], coord[1]]);
        //    marker.bindPopup("Lat: " + coord[0] + " " + "Long: " + coord[1]);
        //    markers.addLayer(marker);
        //}

        //map.addLayer(markers);
        spinner.removeClass('is-active');

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiZ29vb2dpbGkiLCJhIjoiY2o5dHB2eGRtNGZ2cTJxcGdkZWNzbDh0MiJ9.EkOgfmQR4JzFno4YpWMK6A', {
            attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
            minZoom: 5,
            maxZoom: 21,
            id: 'mapbox.streets',
            accessToken: 'pk.eyJ1IjoiZ29vb2dpbGkiLCJhIjoiY2o5dHB2eGRtNGZ2cTJxcGdkZWNzbDh0MiJ9.EkOgfmQR4JzFno4YpWMK6A'
        }).addTo(map);
    }

</script>

Diploma_work/Views/Home/RouteBuilder.cshtml
@{
    ViewBag.Title = "RouteBuilder";
}

<div class="mapContent col-md-12" id="content" style="height: 80vh;">
    @*<div class="loader loader-default"></div>*@
</div>

<script>
    var map = L.map('content');

    L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiZ29vb2dpbGkiLCJhIjoiY2o5dHB2eGRtNGZ2cTJxcGdkZWNzbDh0MiJ9.EkOgfmQR4JzFno4YpWMK6A', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        minZoom: 5,
        maxZoom: 21,
        id: 'mapbox.streets',
        accessToken: 'pk.eyJ1IjoiZ29vb2dpbGkiLCJhIjoiY2o5dHB2eGRtNGZ2cTJxcGdkZWNzbDh0MiJ9.EkOgfmQR4JzFno4YpWMK6A'
    }).addTo(map);

    //L.Control.geocoder().addTo(map);

    L.Routing.control({
        waypoints: [
            L.latLng(57.74, 11.94),
            L.latLng(57.6792, 11.949)
        ],
        routeWhileDragging: true,
        geocoder: L.Control.Geocoder.nominatim()
    }).addTo(map);
</script>